//
// @Author: kamalyes 501893067@qq.com
// @Date: 2026-03-27 00:00:00
// @LastEditors: kamalyes 501893067@qq.com
// @LastEditTime: 2026-03-28 00:00:00
// @Description: 分布式通信协议定义 - Master 与 Worker 之间的 gRPC 消息和服务
//
// 协议架构:
//   ┌─────────────────────────────────────────────────────────┐
//   │                    MasterService                        │
//   │  ┌──────────────┐  ┌──────────────┐  ┌──────────────┐  │
//   │  │ RegisterNode │  │  Heartbeat   │  │UnregisterNode│  │
//   │  │  (Unary RPC) │  │  (Unary RPC) │  │  (Unary RPC) │  │
//   │  └──────────────┘  └──────────────┘  └──────────────┘  │
//   │  ┌──────────────┐  ┌──────────────────────────────────┐ │
//   │  │ReportTaskSts │  │       ConnectStream              │ │
//   │  │  (Unary RPC) │  │  (Bidirectional Streaming)       │ │
//   │  └──────────────┘  │  Worker → Master: WorkerReport   │ │
//   │                     │  Master → Worker: MasterCommand  │ │
//   │                     └──────────────────────────────────┘ │
//   └─────────────────────────────────────────────────────────┘
//   ┌─────────────────────────────────────────────────────────┐
//   │                    WorkerService                        │
//   │  ┌──────────────┐  ┌──────────────┐  ┌──────────────┐  │
//   │  │ DispatchTask │  │  CancelTask  │  │  HealthCheck │  │
//   │  │  (Unary RPC) │  │  (Unary RPC) │  │  (Unary RPC) │  │
//   │  └──────────────┘  └──────────────┘  └──────────────┘  │
//   │  ┌──────────────┐  ┌──────────────┐                    │
//   │  │ QueryTasks   │  │UpdateCapacity│                    │
//   │  │  (Unary RPC) │  │  (Unary RPC) │                    │
//   │  └──────────────┘  └──────────────┘                    │
//   └─────────────────────────────────────────────────────────┘
//
// 通信模式:
//   1. 混合模式（推荐）: ConnectStream 双向流 + WorkerService Unary RPC
//      - 实时任务通过双向流下发，适合高频小任务
//      - 大任务通过 Unary RPC 直接下发，适合低频大任务
//   2. 纯 Unary 模式: 仅使用 WorkerService.DispatchTask
//      - 适合网络环境不稳定、不需要实时推送的场景
//   3. 纯 Stream 模式: 仅使用 ConnectStream
//      - 适合需要持续通信、低延迟的场景
//
// 节点生命周期:
//   注册(Register) → 心跳保活(Heartbeat) → 运行中(Ready)
//     → 排空(Drain) → 注销(Unregister) / 断开(Disconnect)
//     异常: → 重连(Reconnect) → 恢复(Recover)
//
// 任务生命周期:
//   Pending → Scheduled → Dispatched → Running → Succeeded/Failed
//                                  ↘ Timeout    ↘ Cancelled
//                      Failed/Timeout → Retrying → Pending
//
// 连接生命周期:
//   Disconnected → Connecting → Connected → Ready → Draining → Disconnected
//                            ↘ Reconnecting → Connected/Disconnected
//
// Copyright (c) 2026 by kamalyes, All Rights Reserved.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.24.3
// source: proto/distributed.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MasterService_RegisterNode_FullMethodName     = "/distributed.MasterService/RegisterNode"
	MasterService_Heartbeat_FullMethodName        = "/distributed.MasterService/Heartbeat"
	MasterService_UnregisterNode_FullMethodName   = "/distributed.MasterService/UnregisterNode"
	MasterService_ReportTaskStatus_FullMethodName = "/distributed.MasterService/ReportTaskStatus"
	MasterService_ConnectStream_FullMethodName    = "/distributed.MasterService/ConnectStream"
)

// MasterServiceClient is the client API for MasterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MasterService Master 端服务
// Worker 作为客户端调用此服务完成注册、心跳、任务回报等操作
type MasterServiceClient interface {
	// RegisterNode 节点注册
	// Worker 启动后调用，向 Master 注册节点信息
	// 返回认证令牌、心跳间隔和会话 ID
	RegisterNode(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Heartbeat 心跳保活
	// Worker 定期调用，维持连接活性并上报节点状态和容量
	// Master 可通过响应下发控制命令
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// UnregisterNode 节点注销
	// Worker 主动下线时调用，Master 据此重新分配该节点的任务
	// force=false 时 Master 会等待该节点任务完成后再注销
	UnregisterNode(ctx context.Context, in *UnregisterRequest, opts ...grpc.CallOption) (*UnregisterResponse, error)
	// ReportTaskStatus 任务状态回报
	// Worker 通过 Unary RPC 上报任务状态变更
	// 适用于非流式模式或作为流式模式的补充
	ReportTaskStatus(ctx context.Context, in *TaskStatusUpdate, opts ...grpc.CallOption) (*TaskStatusUpdateResponse, error)
	// ConnectStream 双向流式连接
	// Worker 发起，建立持久化的双向通信通道
	// - Worker → Master: 连接请求、心跳、任务状态上报、断开请求、排空完成、容量更新
	// - Master → Worker: 任务下发、取消命令、排空命令、连接确认、断开确认、容量确认
	// 适用于需要实时通信和低延迟任务下发的场景
	// 支持重连恢复：携带 session_id 可恢复之前的会话状态
	ConnectStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerReport, MasterCommand], error)
}

type masterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMasterServiceClient(cc grpc.ClientConnInterface) MasterServiceClient {
	return &masterServiceClient{cc}
}

func (c *masterServiceClient) RegisterNode(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, MasterService_RegisterNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, MasterService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterServiceClient) UnregisterNode(ctx context.Context, in *UnregisterRequest, opts ...grpc.CallOption) (*UnregisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterResponse)
	err := c.cc.Invoke(ctx, MasterService_UnregisterNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterServiceClient) ReportTaskStatus(ctx context.Context, in *TaskStatusUpdate, opts ...grpc.CallOption) (*TaskStatusUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskStatusUpdateResponse)
	err := c.cc.Invoke(ctx, MasterService_ReportTaskStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterServiceClient) ConnectStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerReport, MasterCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MasterService_ServiceDesc.Streams[0], MasterService_ConnectStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WorkerReport, MasterCommand]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MasterService_ConnectStreamClient = grpc.BidiStreamingClient[WorkerReport, MasterCommand]

// MasterServiceServer is the server API for MasterService service.
// All implementations must embed UnimplementedMasterServiceServer
// for forward compatibility.
//
// MasterService Master 端服务
// Worker 作为客户端调用此服务完成注册、心跳、任务回报等操作
type MasterServiceServer interface {
	// RegisterNode 节点注册
	// Worker 启动后调用，向 Master 注册节点信息
	// 返回认证令牌、心跳间隔和会话 ID
	RegisterNode(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// Heartbeat 心跳保活
	// Worker 定期调用，维持连接活性并上报节点状态和容量
	// Master 可通过响应下发控制命令
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// UnregisterNode 节点注销
	// Worker 主动下线时调用，Master 据此重新分配该节点的任务
	// force=false 时 Master 会等待该节点任务完成后再注销
	UnregisterNode(context.Context, *UnregisterRequest) (*UnregisterResponse, error)
	// ReportTaskStatus 任务状态回报
	// Worker 通过 Unary RPC 上报任务状态变更
	// 适用于非流式模式或作为流式模式的补充
	ReportTaskStatus(context.Context, *TaskStatusUpdate) (*TaskStatusUpdateResponse, error)
	// ConnectStream 双向流式连接
	// Worker 发起，建立持久化的双向通信通道
	// - Worker → Master: 连接请求、心跳、任务状态上报、断开请求、排空完成、容量更新
	// - Master → Worker: 任务下发、取消命令、排空命令、连接确认、断开确认、容量确认
	// 适用于需要实时通信和低延迟任务下发的场景
	// 支持重连恢复：携带 session_id 可恢复之前的会话状态
	ConnectStream(grpc.BidiStreamingServer[WorkerReport, MasterCommand]) error
	mustEmbedUnimplementedMasterServiceServer()
}

// UnimplementedMasterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMasterServiceServer struct{}

func (UnimplementedMasterServiceServer) RegisterNode(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterNode not implemented")
}
func (UnimplementedMasterServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedMasterServiceServer) UnregisterNode(context.Context, *UnregisterRequest) (*UnregisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnregisterNode not implemented")
}
func (UnimplementedMasterServiceServer) ReportTaskStatus(context.Context, *TaskStatusUpdate) (*TaskStatusUpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportTaskStatus not implemented")
}
func (UnimplementedMasterServiceServer) ConnectStream(grpc.BidiStreamingServer[WorkerReport, MasterCommand]) error {
	return status.Error(codes.Unimplemented, "method ConnectStream not implemented")
}
func (UnimplementedMasterServiceServer) mustEmbedUnimplementedMasterServiceServer() {}
func (UnimplementedMasterServiceServer) testEmbeddedByValue()                       {}

// UnsafeMasterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MasterServiceServer will
// result in compilation errors.
type UnsafeMasterServiceServer interface {
	mustEmbedUnimplementedMasterServiceServer()
}

func RegisterMasterServiceServer(s grpc.ServiceRegistrar, srv MasterServiceServer) {
	// If the following call panics, it indicates UnimplementedMasterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MasterService_ServiceDesc, srv)
}

func _MasterService_RegisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServiceServer).RegisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterService_RegisterNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServiceServer).RegisterNode(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterService_UnregisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServiceServer).UnregisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterService_UnregisterNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServiceServer).UnregisterNode(ctx, req.(*UnregisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterService_ReportTaskStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskStatusUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServiceServer).ReportTaskStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MasterService_ReportTaskStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServiceServer).ReportTaskStatus(ctx, req.(*TaskStatusUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _MasterService_ConnectStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MasterServiceServer).ConnectStream(&grpc.GenericServerStream[WorkerReport, MasterCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MasterService_ConnectStreamServer = grpc.BidiStreamingServer[WorkerReport, MasterCommand]

// MasterService_ServiceDesc is the grpc.ServiceDesc for MasterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MasterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "distributed.MasterService",
	HandlerType: (*MasterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterNode",
			Handler:    _MasterService_RegisterNode_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _MasterService_Heartbeat_Handler,
		},
		{
			MethodName: "UnregisterNode",
			Handler:    _MasterService_UnregisterNode_Handler,
		},
		{
			MethodName: "ReportTaskStatus",
			Handler:    _MasterService_ReportTaskStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ConnectStream",
			Handler:       _MasterService_ConnectStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/distributed.proto",
}

const (
	WorkerService_DispatchTask_FullMethodName   = "/distributed.WorkerService/DispatchTask"
	WorkerService_CancelTask_FullMethodName     = "/distributed.WorkerService/CancelTask"
	WorkerService_HealthCheck_FullMethodName    = "/distributed.WorkerService/HealthCheck"
	WorkerService_QueryTasks_FullMethodName     = "/distributed.WorkerService/QueryTasks"
	WorkerService_UpdateCapacity_FullMethodName = "/distributed.WorkerService/UpdateCapacity"
)

// WorkerServiceClient is the client API for WorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WorkerService Worker 端服务
// Master 作为客户端调用此服务完成任务的直接下发、取消和健康检查
// Worker 需要启动独立的 gRPC 服务器来接收这些请求
type WorkerServiceClient interface {
	// DispatchTask 任务下发（Unary RPC）
	// Master 直接向 Worker 下发任务
	// 适用于大任务、低频任务或双向流不可用的降级场景
	// Worker 返回是否接受该任务
	DispatchTask(ctx context.Context, in *DispatchTaskRequest, opts ...grpc.CallOption) (*DispatchTaskResponse, error)
	// CancelTask 取消任务（Unary RPC）
	// Master 通知 Worker 取消正在执行的任务
	// Worker 收到后应中断任务执行并释放资源
	// force=true 时 Worker 应立即终止，不等优雅退出
	CancelTask(ctx context.Context, in *CancelTaskRequest, opts ...grpc.CallOption) (*CancelTaskResponse, error)
	// HealthCheck 健康检查（Unary RPC）
	// Master 主动探测 Worker 存活状态
	// 用于心跳超时后的二次确认或运维巡检
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// QueryTasks 查询任务（Unary RPC）
	// Master 查询 Worker 上运行中的任务列表
	// 用于故障恢复、任务迁移前的状态确认
	QueryTasks(ctx context.Context, in *QueryTasksRequest, opts ...grpc.CallOption) (*QueryTasksResponse, error)
	// UpdateCapacity 更新容量（Unary RPC）
	// Worker 通过 Unary RPC 主动上报容量变化
	// 作为双向流容量更新的补充，适用于非流式模式
	UpdateCapacity(ctx context.Context, in *UpdateCapacityRequest, opts ...grpc.CallOption) (*UpdateCapacityResponse, error)
}

type workerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerServiceClient(cc grpc.ClientConnInterface) WorkerServiceClient {
	return &workerServiceClient{cc}
}

func (c *workerServiceClient) DispatchTask(ctx context.Context, in *DispatchTaskRequest, opts ...grpc.CallOption) (*DispatchTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DispatchTaskResponse)
	err := c.cc.Invoke(ctx, WorkerService_DispatchTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) CancelTask(ctx context.Context, in *CancelTaskRequest, opts ...grpc.CallOption) (*CancelTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelTaskResponse)
	err := c.cc.Invoke(ctx, WorkerService_CancelTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, WorkerService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) QueryTasks(ctx context.Context, in *QueryTasksRequest, opts ...grpc.CallOption) (*QueryTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryTasksResponse)
	err := c.cc.Invoke(ctx, WorkerService_QueryTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) UpdateCapacity(ctx context.Context, in *UpdateCapacityRequest, opts ...grpc.CallOption) (*UpdateCapacityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCapacityResponse)
	err := c.cc.Invoke(ctx, WorkerService_UpdateCapacity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerServiceServer is the server API for WorkerService service.
// All implementations must embed UnimplementedWorkerServiceServer
// for forward compatibility.
//
// WorkerService Worker 端服务
// Master 作为客户端调用此服务完成任务的直接下发、取消和健康检查
// Worker 需要启动独立的 gRPC 服务器来接收这些请求
type WorkerServiceServer interface {
	// DispatchTask 任务下发（Unary RPC）
	// Master 直接向 Worker 下发任务
	// 适用于大任务、低频任务或双向流不可用的降级场景
	// Worker 返回是否接受该任务
	DispatchTask(context.Context, *DispatchTaskRequest) (*DispatchTaskResponse, error)
	// CancelTask 取消任务（Unary RPC）
	// Master 通知 Worker 取消正在执行的任务
	// Worker 收到后应中断任务执行并释放资源
	// force=true 时 Worker 应立即终止，不等优雅退出
	CancelTask(context.Context, *CancelTaskRequest) (*CancelTaskResponse, error)
	// HealthCheck 健康检查（Unary RPC）
	// Master 主动探测 Worker 存活状态
	// 用于心跳超时后的二次确认或运维巡检
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// QueryTasks 查询任务（Unary RPC）
	// Master 查询 Worker 上运行中的任务列表
	// 用于故障恢复、任务迁移前的状态确认
	QueryTasks(context.Context, *QueryTasksRequest) (*QueryTasksResponse, error)
	// UpdateCapacity 更新容量（Unary RPC）
	// Worker 通过 Unary RPC 主动上报容量变化
	// 作为双向流容量更新的补充，适用于非流式模式
	UpdateCapacity(context.Context, *UpdateCapacityRequest) (*UpdateCapacityResponse, error)
	mustEmbedUnimplementedWorkerServiceServer()
}

// UnimplementedWorkerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerServiceServer struct{}

func (UnimplementedWorkerServiceServer) DispatchTask(context.Context, *DispatchTaskRequest) (*DispatchTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DispatchTask not implemented")
}
func (UnimplementedWorkerServiceServer) CancelTask(context.Context, *CancelTaskRequest) (*CancelTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelTask not implemented")
}
func (UnimplementedWorkerServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedWorkerServiceServer) QueryTasks(context.Context, *QueryTasksRequest) (*QueryTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryTasks not implemented")
}
func (UnimplementedWorkerServiceServer) UpdateCapacity(context.Context, *UpdateCapacityRequest) (*UpdateCapacityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCapacity not implemented")
}
func (UnimplementedWorkerServiceServer) mustEmbedUnimplementedWorkerServiceServer() {}
func (UnimplementedWorkerServiceServer) testEmbeddedByValue()                       {}

// UnsafeWorkerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerServiceServer will
// result in compilation errors.
type UnsafeWorkerServiceServer interface {
	mustEmbedUnimplementedWorkerServiceServer()
}

func RegisterWorkerServiceServer(s grpc.ServiceRegistrar, srv WorkerServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkerService_ServiceDesc, srv)
}

func _WorkerService_DispatchTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).DispatchTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_DispatchTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).DispatchTask(ctx, req.(*DispatchTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_CancelTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).CancelTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_CancelTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).CancelTask(ctx, req.(*CancelTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_QueryTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).QueryTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_QueryTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).QueryTasks(ctx, req.(*QueryTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_UpdateCapacity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCapacityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).UpdateCapacity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_UpdateCapacity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).UpdateCapacity(ctx, req.(*UpdateCapacityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkerService_ServiceDesc is the grpc.ServiceDesc for WorkerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "distributed.WorkerService",
	HandlerType: (*WorkerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DispatchTask",
			Handler:    _WorkerService_DispatchTask_Handler,
		},
		{
			MethodName: "CancelTask",
			Handler:    _WorkerService_CancelTask_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _WorkerService_HealthCheck_Handler,
		},
		{
			MethodName: "QueryTasks",
			Handler:    _WorkerService_QueryTasks_Handler,
		},
		{
			MethodName: "UpdateCapacity",
			Handler:    _WorkerService_UpdateCapacity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/distributed.proto",
}

const (
	AdminService_ListNodes_FullMethodName       = "/distributed.AdminService/ListNodes"
	AdminService_GetNodeInfo_FullMethodName     = "/distributed.AdminService/GetNodeInfo"
	AdminService_GetClusterStats_FullMethodName = "/distributed.AdminService/GetClusterStats"
	AdminService_ListTasks_FullMethodName       = "/distributed.AdminService/ListTasks"
	AdminService_DrainNode_FullMethodName       = "/distributed.AdminService/DrainNode"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AdminService 集群管理服务
// 提供类似 kubectl 的集群管理 API
// 可由运维工具、CLI、Dashboard 等调用
type AdminServiceClient interface {
	// ListNodes 列出节点（类似 kubectl get nodes）
	// 支持按状态、区域、标签过滤，支持分页
	ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error)
	// GetNodeInfo 获取节点详情
	// 返回节点的完整信息，包括容量、连接状态、任务数等
	GetNodeInfo(ctx context.Context, in *GetNodeInfoRequest, opts ...grpc.CallOption) (*GetNodeInfoResponse, error)
	// GetClusterStats 获取集群统计（类似 kubectl top nodes）
	// 返回集群级别的聚合统计信息
	GetClusterStats(ctx context.Context, in *ClusterStatsRequest, opts ...grpc.CallOption) (*ClusterStatsResponse, error)
	// ListTasks 列出任务（类似 kubectl get jobs）
	// 支持按状态、类型、节点过滤，支持分页
	ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error)
	// DrainNode 排空节点（类似 kubectl drain）
	// 通知指定节点停止接受新任务，等待已有任务完成后下线
	DrainNode(ctx context.Context, in *DrainNodeRequest, opts ...grpc.CallOption) (*DrainNodeResponse, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNodesResponse)
	err := c.cc.Invoke(ctx, AdminService_ListNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetNodeInfo(ctx context.Context, in *GetNodeInfoRequest, opts ...grpc.CallOption) (*GetNodeInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeInfoResponse)
	err := c.cc.Invoke(ctx, AdminService_GetNodeInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetClusterStats(ctx context.Context, in *ClusterStatsRequest, opts ...grpc.CallOption) (*ClusterStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterStatsResponse)
	err := c.cc.Invoke(ctx, AdminService_GetClusterStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTasksResponse)
	err := c.cc.Invoke(ctx, AdminService_ListTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) DrainNode(ctx context.Context, in *DrainNodeRequest, opts ...grpc.CallOption) (*DrainNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DrainNodeResponse)
	err := c.cc.Invoke(ctx, AdminService_DrainNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility.
//
// AdminService 集群管理服务
// 提供类似 kubectl 的集群管理 API
// 可由运维工具、CLI、Dashboard 等调用
type AdminServiceServer interface {
	// ListNodes 列出节点（类似 kubectl get nodes）
	// 支持按状态、区域、标签过滤，支持分页
	ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error)
	// GetNodeInfo 获取节点详情
	// 返回节点的完整信息，包括容量、连接状态、任务数等
	GetNodeInfo(context.Context, *GetNodeInfoRequest) (*GetNodeInfoResponse, error)
	// GetClusterStats 获取集群统计（类似 kubectl top nodes）
	// 返回集群级别的聚合统计信息
	GetClusterStats(context.Context, *ClusterStatsRequest) (*ClusterStatsResponse, error)
	// ListTasks 列出任务（类似 kubectl get jobs）
	// 支持按状态、类型、节点过滤，支持分页
	ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error)
	// DrainNode 排空节点（类似 kubectl drain）
	// 通知指定节点停止接受新任务，等待已有任务完成后下线
	DrainNode(context.Context, *DrainNodeRequest) (*DrainNodeResponse, error)
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminServiceServer struct{}

func (UnimplementedAdminServiceServer) ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNodes not implemented")
}
func (UnimplementedAdminServiceServer) GetNodeInfo(context.Context, *GetNodeInfoRequest) (*GetNodeInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodeInfo not implemented")
}
func (UnimplementedAdminServiceServer) GetClusterStats(context.Context, *ClusterStatsRequest) (*ClusterStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClusterStats not implemented")
}
func (UnimplementedAdminServiceServer) ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedAdminServiceServer) DrainNode(context.Context, *DrainNodeRequest) (*DrainNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DrainNode not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}
func (UnimplementedAdminServiceServer) testEmbeddedByValue()                      {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	// If the following call panics, it indicates UnimplementedAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListNodes(ctx, req.(*ListNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetNodeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetNodeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetNodeInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetNodeInfo(ctx, req.(*GetNodeInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetClusterStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetClusterStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_GetClusterStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetClusterStats(ctx, req.(*ClusterStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_ListTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ListTasks(ctx, req.(*ListTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_DrainNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrainNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).DrainNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_DrainNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).DrainNode(ctx, req.(*DrainNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "distributed.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListNodes",
			Handler:    _AdminService_ListNodes_Handler,
		},
		{
			MethodName: "GetNodeInfo",
			Handler:    _AdminService_GetNodeInfo_Handler,
		},
		{
			MethodName: "GetClusterStats",
			Handler:    _AdminService_GetClusterStats_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _AdminService_ListTasks_Handler,
		},
		{
			MethodName: "DrainNode",
			Handler:    _AdminService_DrainNode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/distributed.proto",
}
